### ISSUE TITLE
3_small_graph_batching_with_padding.ipynb has JavaScript error

### ISSUE THREAD

**Issue by nmb-paperspace** [graphcore/Gradient-Pytorch-Geometric#10]
In `learning-pytorch-geometric-on-ipus/3_small_graph_batching_with_padding.ipynb`

Cell 5 `def molecule_converter(...` has a JavaScript error

```
Model class 'OutputModel' from module '@jupyter-widgets/output' is loaded but can not be instantiated
TypeError: Cannot read properties of undefined (reading 'sessionContext')
    at u.initialize (https://console.paperspace.com/ide/vendors-f64a56cf.7db820de113321a55e18.js:2:159546)
    at new e.Model (https://console.paperspace.com/ide/vendors-c30f4496.7db820de113321a55e18.js:2:483011)
    at new u (https://console.paperspace.com/ide/vendors-f64a56cf.7db820de113321a55e18.js:2:159298)
    at z._make_model (https://console.paperspace.com/ide/vendors-f64a56cf.7db820de113321a55e18.js:2:11894)
<function __main__.conf_viewer(idx)>
```

**Comment by evawGraphcore** [comment]
Hi, I’m unable to reproduce these errors. Can you give me more information on the runtime details? Which image is your container pointing to? Which machine type are you running on?
